import { PaymentIntentId } from '../domain/ids';
import { PaymentRequirement } from '../domain/models';

export interface GetOrCreatePaymentIntentCommand {
  idempotencyKey: string;
  buyerKey: string;
  jobType: string;
  inputHash: string;
  price: {
    amount: string;
    currency: string;
  };
  payload: Record<string, any>;
  
  /**
   * The payment requirement generated by the application layer/payment adapter.
   * Cleared Core stores this to ensure consistency.
   */
  paymentRequirement: PaymentRequirement;
}

export interface GetOrCreatePaymentIntentResult {
  paymentIntentId: PaymentIntentId;
  paymentRequirement: PaymentRequirement;
  price: {
    amount: string;
    currency: string;
  };
  expiresAt: Date;
}
