export enum QuoteStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
  REJECTED = 'REJECTED',
}

export enum JobStatus {
  PENDING_FUNDING = 'PENDING_FUNDING',
  ADMITTED = 'ADMITTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum EscrowState {
  NONE = 'NONE',
  PENDING = 'PENDING',
  HELD = 'HELD',
  RELEASED = 'RELEASED',
  REFUNDED = 'REFUNDED',
}

export enum ResolutionState {
  UNRESOLVED = 'UNRESOLVED',
  RESOLVED_SUCCESS = 'RESOLVED_SUCCESS',
  RESOLVED_FAILURE = 'RESOLVED_FAILURE',
  DISPUTED = 'DISPUTED',
}

export enum AttemptStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  TIMED_OUT = 'TIMED_OUT',
}
