export enum PaymentIntentStatus {
  OPEN = 'OPEN',
  FUNDED = 'FUNDED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum JobStatus {
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
  FUNDED = 'FUNDED',
  DISPATCHED = 'DISPATCHED',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  RESOLUTION_REQUIRED = 'RESOLUTION_REQUIRED',
}

export enum EscrowState {
  NOT_FUNDED = 'NOT_FUNDED',
  HELD = 'HELD',
  RELEASE_PENDING = 'RELEASE_PENDING',
  RELEASED = 'RELEASED',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUNDED = 'REFUNDED',
}

export enum ResolutionState {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUNDED = 'REFUNDED',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
}

export enum AttemptStatus {
  DISPATCHED = 'DISPATCHED',
  RUNNING = 'RUNNING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  TIMED_OUT = 'TIMED_OUT',
  ABORTED = 'ABORTED',
}
